extends Node

const UNIQUE_EXPANSION_CARDS := 6

enum CARD { USB_C, USB_A, HDMI, ETHERNET, DISPLAY_PORT, MICRO_SD, SD, STORAGE }
enum SLOT { TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT }

var card_names := {
	CARD.USB_C: "UsbCExpansionCard",
	CARD.USB_A: "UsbA_HDMI_DP",
	CARD.HDMI: "UsbA_HDMI_DP",
	CARD.ETHERNET: "EthernetExpansionCard",
	CARD.DISPLAY_PORT: "UsbA_HDMI_DP",
	CARD.MICRO_SD: "MicroSDExpansionCard",
	CARD.SD: "SDExpansionCard",
	CARD.STORAGE: "StorageExpansionCard",
}

var cns := {
	CARD.USB_C: "USB-C",
	CARD.USB_A: "USB-A",
	CARD.HDMI: "HDMI",
	CARD.ETHERNET: "Ethernet",
	CARD.DISPLAY_PORT: "DisplayPort",
	CARD.MICRO_SD: "MicroSD",
	CARD.SD: "SD",
	CARD.STORAGE: "Storage",
}

var review := {
	1: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	2: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	3: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	4: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	5: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	6: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	7: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	8: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	9: {
		"message": null,
		"correct": [],
		"wrong": [],
	},
	10: {
		"message": null,
		"correct": [],
		"wrong": [],
	}
}

var level := 1
var request
# Messages generated by Deepseek
var m := [
	{
	  "name": "Chloe Rodriguez",
	  "message": "Hey! So excited for my new Framework! I just need to connect my drawing tablet and my external hard drive where I keep all my design files. Maybe an extra port for my phone cable too? That's pretty much it!",
	  "correct": [CARD.USB_C, CARD.USB_A, CARD.STORAGE]
	},
	{
	  "name": "Marcus Chen",
	  "message": "My workflow requires connecting to dual 4K monitors for coding and documentation simultaneously. Also need reliable internet for video calls with offshore teams - WiFi can be spotty near the windows. Keep it clean and professional.",
	  "correct": [CARD.HDMI, CARD.DISPLAY_PORT, CARD.ETHERNET]
	},
	{
	  "name": "Priya Sharma",
	  "message": "As content lead, I transfer massive video files from my mirrorless camera daily. Need fast transfer options and backup for SD cards immediately after shoots. Also connecting to conference room projector for weekly reviews.",
	  "correct": [CARD.USB_C, CARD.SD, CARD.HDMI, CARD.STORAGE]
	},
	{
	  "name": "Anders Bjornsson",
	  "message": "Archaeology department - I'm constantly digitizing field research. Need to connect multiple legacy devices from dig sites, transfer from various memory card types used in cameras and equipment, and hook up to the university's ethernet-only network for database access.",
	  "correct": [CARD.USB_A, CARD.MICRO_SD, CARD.SD, CARD.ETHERNET]
	},
	{
	  "name": "Eleanor Vanderbilt-Smythe",
	  "message": "Darling, I'm overseeing the merger acquisition and need EVERY connection possible. Must interface with 90s corporate relics, modern investor tablets, the boardroom's peculiar display system, and transfer sensitive documents from... let's call them 'vintage' storage mediums. Surprise me.",
	  "correct": [CARD.USB_C, CARD.USB_A, CARD.HDMI, CARD.DISPLAY_PORT, CARD.ETHERNET, CARD.MICRO_SD, CARD.SD, CARD.STORAGE]
	},
	{
	  "name": "Jasmine Lee",
	  "message": "Photographer here! Need to dump photos from my camera's SD card, connect my color-calibrated monitor, and hook up my external SSD for editing. Maybe one more for my Wacom tablet?",
	  "correct": [CARD.SD, CARD.DISPLAY_PORT, CARD.STORAGE, CARD.USB_C]
	},
	{
	  "name": "Diego Silva",
	  "message": "I do a lot of presentations. Need to connect to projectors and large TVs in conference rooms. Also, a reliable internet port is a must for live demos - can't risk WiFi drops!",
	  "correct": [CARD.HDMI, CARD.ETHERNET, CARD.USB_C]
	},
	{
	  "name": "Aisha Khan",
	  "message": "Podcast producer! I need to connect my high-quality audio interface, a second screen for editing timelines, and my massive hard drive library of audio samples and interviews.",
	  "correct": [CARD.USB_A, CARD.DISPLAY_PORT, CARD.STORAGE]
	},
	{
	  "name": "Felix Weber",
	  "message": "I'm in finance and need to run multiple trading platforms. That means connecting to two high-refresh-rate monitors and a wired ethernet connection for the fastest possible data throughput. No compromises.",
	  "correct": [CARD.DISPLAY_PORT, CARD.DISPLAY_PORT, CARD.ETHERNET]
	},
	{
	  "name": "Anya Petrova",
	  "message": "As a researcher, I use legacy lab equipment that only has old USB ports. I also need to transfer data from sensor arrays on microSD and present my findings on a monitor. Very specific needs!",
	  "correct": [CARD.USB_A, CARD.MICRO_SD, CARD.HDMI]
	},
	{
	  "name": "Ben Carter",
	  "message": "IT guy. I need to image machines, which means booting from USB drives (the old, rectangular kind). Also need an HDMI port for troubleshooting displays and ethernet for network diagnostics.",
	  "correct": [CARD.USB_A, CARD.HDMI, CARD.ETHERNET]
	},
	{
	  "name": "Olivia Green",
	  "message": "Graphic designer! I need to connect my Cintiq display, my external backup drive, and my iPad for sidecar. All my dongles are a mess, so built-in ports would be a dream.",
	  "correct": [CARD.USB_C, CARD.DISPLAY_PORT, CARD.STORAGE]
	},
	{
	  "name": "Kenji Tanaka",
	  "message": "I develop mobile games. Need to connect test Android and iOS devices simultaneously, hook up a 4K monitor, and have a fast SD card reader for asset transfers from the art team.",
	  "correct": [CARD.USB_C, CARD.USB_A, CARD.DISPLAY_PORT, CARD.SD]
	},
	{
	  "name": "Maya Papadopoulos",
	  "message": "Travel blogger here! I'm constantly transferring photos and videos from my drone (microSD), my GoPro (SD), and my camera (SD). Also need to back everything up to a portable drive on the go.",
	  "correct": [CARD.MICRO_SD, CARD.SD, CARD.STORAGE]
	},
	{
	  "name": "Caleb Jones",
	  "message": "Video editor. My workflow requires two high-resolution monitors, a super-fast connection to my RAID storage array, and a card reader for footage. Speed is everything.",
	  "correct": [CARD.DISPLAY_PORT, CARD.HDMI, CARD.STORAGE, CARD.SD]
	},
	{
	  "name": "Sofia Rossi",
	  "message": "I'm in sales and live on video calls. I need a rock-solid ethernet connection, a port for the company monitor, and the ability to plug in my headset dongle and phone at the same time.",
	  "correct": [CARD.ETHERNET, CARD.HDMI, CARD.USB_A]
	},
	{
	  "name": "Lars Olsson",
	  "message": "Sound engineer. My audio interface uses USB-A, I need a second display for my mixing console software, and I transfer large session files from SD cards. Keep the signal path clean!",
	  "correct": [CARD.USB_A, CARD.DISPLAY_PORT, CARD.SD]
	},
	{
	  "name": "Zara Ali",
	  "message": "Architect. I need to connect to large-format plotters, a high-res secondary display for renders, and have multiple ports for various model scanner dongles and hard drives. A hub life is not for me.",
	  "correct": [CARD.USB_A, CARD.USB_C, CARD.DISPLAY_PORT, CARD.STORAGE]
	},
	{
	  "name": "Ethan Moore",
	  "message": "Gamer and streamer. I need to connect my high-refresh-rate gaming monitor, my stream deck, my external capture card, and ensure I have a wired internet connection for low latency.",
	  "correct": [CARD.DISPLAY_PORT, CARD.USB_A, CARD.USB_C, CARD.ETHERNET]
	},
	{
	  "name": "Isabelle Laurent",
	  "message": "Fashion photographer. Between the SD cards from my camera, the CFexpress reader that uses USB-C, and the external display for clients, I need a versatile setup. Style and function!",
	  "correct": [CARD.SD, CARD.USB_C, CARD.HDMI]
	},
	{
	  "name": "Rohan Desai",
	  "message": "Data scientist. I run simulations that require a fast connection to a network-attached storage server and often present on two screens. Some of our data loggers still use microSD cards.",
	  "correct": [CARD.ETHERNET, CARD.DISPLAY_PORT, CARD.HDMI, CARD.MICRO_SD]
	},
	{
	  "name": "Chloe Zhang",
	  "message": "UX designer. I need to connect my high-DPI monitor for design work, my iPad for prototyping, and my iPhone for testing. A fast SSD for my design library is also essential.",
	  "correct": [CARD.USB_C, CARD.DISPLAY_PORT, CARD.STORAGE]
	},
	{
	  "name": "Oscar Martinez",
	  "message": "Field journalist. My kit includes a satellite modem (ethernet), a camera (SD), and a backup power bank (USB-C). I need to file stories and transfer media from anywhere, reliably.",
	  "correct": [CARD.ETHERNET, CARD.SD, CARD.USB_C]
	},
	{
	  "name": "Leila Abara",
	  "message": "VR developer. I need multiple high-speed ports for the VR headset link, an additional monitor for coding, and fast storage for massive asset files. Bandwidth is critical.",
	  "correct": [CARD.USB_C, CARD.USB_C, CARD.DISPLAY_PORT, CARD.STORAGE]
	},
	{
	  "name": "Nicolas Vega",
	  "message": "Music producer. My studio setup requires connecting an audio interface (USB-A), an external display, and multiple large hard drives for sample libraries and project files. No room for lag.",
	  "correct": [CARD.USB_A, CARD.DISPLAY_PORT, CARD.STORAGE, CARD.STORAGE]
	},
	{
	  "name": "Anika Sharma",
	  "message": "Social media manager. I'm always downloading content from phones (USB-C), cameras (SD), and using a second screen to manage multiple platforms. An extra port for a lighting accessory would be great!",
	  "correct": [CARD.USB_C, CARD.SD, CARD.HDMI, CARD.USB_A]
	},
	{
	  "name": "Tobias Schmidt",
	  "message": "Security analyst. My work requires isolated networks (ethernet), multiple air-gapped storage devices, and the ability to read various forms of media from... let's say 'diverse sources'.",
	  "correct": [CARD.ETHERNET, CARD.STORAGE, CARD.STORAGE, CARD.SD]
	},
	{
	  "name": "Elara Vesper",
	  "message": "Astrophotographer. My telescope camera uses a special USB-3 connection, I use an SD card for my DSLR, and I need to run two monitors for processing deep-space images over long nights.",
	  "correct": [CARD.USB_A, CARD.SD, CARD.DISPLAY_PORT, CARD.HDMI]
	},
	{
	  "name": "Jin-ho Park",
	  "message": "Esports coach. I need to capture gameplay footage (HDMI in), connect to a low-latency monitor, use a wired network, and have a port for my proprietary comms device. Every millisecond counts.",
	  "correct": [CARD.HDMI, CARD.DISPLAY_PORT, CARD.ETHERNET, CARD.USB_A]
	},
	{
	  "name": "Gabriela Costa",
	  "message": "Documentary filmmaker. On location, I need to offload footage from SD and microSD cards, power my devices via USB-C, and sometimes connect to a portable monitor for rough edits. Durability and versatility.",
	  "correct": [CARD.SD, CARD.MICRO_SD, CARD.USB_C, CARD.HDMI]
	}
 ]
var messages := m


func reset() -> void:
	review = {
		1: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		2: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		3: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		4: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		5: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		6: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		7: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		8: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		9: {
			"message": null,
			"correct": [],
			"wrong": [],
		},
		10: {
			"message": null,
			"correct": [],
			"wrong": [],
		}
	}

	level = 1
	request = null
	messages = m
